server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: applicationService
          uri: http://localhost:8081/
          predicates:
            - Path=/application/**
        - id: reportservice
          uri: http://localhost:8082/
          predicates:
            - Path=/report/**